// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="@niibase/uniwind/types" />

declare module '@niibase/uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'premium']
    }
}

export {}
