# git-cliff configuration
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "uni-stack"
repo = "uniwind"

[changelog]
body = """
{% if version -%}
  ## What's Changed in {{ version | trim_start_matches(pat="v") }}
{% else -%}
  ## Unreleased
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group }}
  {% for commit in commits %}
    {%- if commit.remote.pr_title -%}
      {%- set commit_message = commit.remote.pr_title -%}
    {%- else -%}
      {%- set commit_message = commit.message -%}
    {%- endif -%}
    * {{ commit_message | split(pat="\n") | first | trim }}\
      {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
      {% if commit.remote.pr_number %} in \
        [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }})\
      {%- endif %}
  {%- endfor %}
{% endfor -%}

{%- if github -%}
  {%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ### New Contributors
  {%- endif %}
  {%- for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution\
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }})\
    {%- endif %}
  {%- endfor %}
{%- endif %}

{%- if previous.version %}
**Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
{%- endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^perf", group = "Performance" },
  { message = "^docs?", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore", group = "Chores" },
  { body = ".*", group = "Other" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"
