import fs from 'fs'
import { packageName } from '../metro/packageName'

export const buildDtsFile = (dtsPath: string, stringifiedThemes: string) => {
    const oldDtsContent = fs.existsSync(dtsPath)
        ? fs.readFileSync(dtsPath, 'utf-8')
        : ''
    const dtsContent = [
        `// NOTE: This file is generated by ${packageName} and it should not be edited manually.`,
        `/// <reference types="${packageName}/types" />`,
        '',
        `declare module '${packageName}' {`,
        `    export interface UniwindConfig {`,
        `        themes: readonly ${stringifiedThemes}`,
        `    }`,
        `}`,
        '',
        `export {}`,
        '',
    ].join('\n')

    if (oldDtsContent === dtsContent) {
        return
    }

    fs.writeFileSync(dtsPath, dtsContent)
}
